# Use root/example as user/password credentials
version: '2.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: 'Bikekingdom'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql
#  # Names our volume
#  volumes:
#    my-db:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
